# Generated by Django 6.0.3 on 2026-03-09 14:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wstgtest_reference_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(upload_to=core.models.evidence_upload_path),
        ),
    ]
